/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiAssessmentQuizRouteImport } from './routes/ai-assessment-quiz'
import { Route as CompetencyAssessmentRouteImport } from './routes/competency-assessment'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LearningPathsRouteImport } from './routes/learning-paths'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SkillGapAnalysisRouteImport } from './routes/skill-gap-analysis'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssessmentQuizRoute = AiAssessmentQuizRouteImport.update({
  id: '/ai-assessment-quiz',
  path: '/ai-assessment-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetencyAssessmentRoute = CompetencyAssessmentRouteImport.update({
  id: '/competency-assessment',
  path: '/competency-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningPathsRoute = LearningPathsRouteImport.update({
  id: '/learning-paths',
  path: '/learning-paths',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillGapAnalysisRoute = SkillGapAnalysisRouteImport.update({
  id: '/skill-gap-analysis',
  path: '/skill-gap-analysis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assessment-quiz': typeof AiAssessmentQuizRoute
  '/competency-assessment': typeof CompetencyAssessmentRoute
  '/dashboard': typeof DashboardRoute
  '/learning-paths': typeof LearningPathsRoute
  '/login': typeof LoginRoute
  '/skill-gap-analysis': typeof SkillGapAnalysisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assessment-quiz': typeof AiAssessmentQuizRoute
  '/competency-assessment': typeof CompetencyAssessmentRoute
  '/dashboard': typeof DashboardRoute
  '/learning-paths': typeof LearningPathsRoute
  '/login': typeof LoginRoute
  '/skill-gap-analysis': typeof SkillGapAnalysisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-assessment-quiz': typeof AiAssessmentQuizRoute
  '/competency-assessment': typeof CompetencyAssessmentRoute
  '/dashboard': typeof DashboardRoute
  '/learning-paths': typeof LearningPathsRoute
  '/login': typeof LoginRoute
  '/skill-gap-analysis': typeof SkillGapAnalysisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assessment-quiz'
    | '/competency-assessment'
    | '/dashboard'
    | '/learning-paths'
    | '/login'
    | '/skill-gap-analysis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assessment-quiz'
    | '/competency-assessment'
    | '/dashboard'
    | '/learning-paths'
    | '/login'
    | '/skill-gap-analysis'
  id:
    | '__root__'
    | '/'
    | '/ai-assessment-quiz'
    | '/competency-assessment'
    | '/dashboard'
    | '/learning-paths'
    | '/login'
    | '/skill-gap-analysis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAssessmentQuizRoute: typeof AiAssessmentQuizRoute
  CompetencyAssessmentRoute: typeof CompetencyAssessmentRoute
  DashboardRoute: typeof DashboardRoute
  LearningPathsRoute: typeof LearningPathsRoute
  LoginRoute: typeof LoginRoute
  SkillGapAnalysisRoute: typeof SkillGapAnalysisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assessment-quiz': {
      id: '/ai-assessment-quiz'
      path: '/ai-assessment-quiz'
      fullPath: '/ai-assessment-quiz'
      preLoaderRoute: typeof AiAssessmentQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competency-assessment': {
      id: '/competency-assessment'
      path: '/competency-assessment'
      fullPath: '/competency-assessment'
      preLoaderRoute: typeof CompetencyAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-paths': {
      id: '/learning-paths'
      path: '/learning-paths'
      fullPath: '/learning-paths'
      preLoaderRoute: typeof LearningPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-gap-analysis': {
      id: '/skill-gap-analysis'
      path: '/skill-gap-analysis'
      fullPath: '/skill-gap-analysis'
      preLoaderRoute: typeof SkillGapAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAssessmentQuizRoute: AiAssessmentQuizRoute,
  CompetencyAssessmentRoute: CompetencyAssessmentRoute,
  DashboardRoute: DashboardRoute,
  LearningPathsRoute: LearningPathsRoute,
  LoginRoute: LoginRoute,
  SkillGapAnalysisRoute: SkillGapAnalysisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
